version: "0.2"
ignorePaths: []
dictionaryDefinitions:
  - name: custom-dictionary
    path: ./.cspell/custom-dictionary.txt
    addWords: true
dictionaries:
  - custom-dictionary
  - softwareTerms
  - software-tools
  - en-gb
  - cpp
  - cpp-legacy
  - cpp-compound-words
words: [questkeeper]
ignoreWords: []
allowCompoundWords: false
import: []
